build: "off"

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - pip --version
  - pip install "pipenv<11.10"
  - pipenv --version
  - pipenv install --dev --skip-lock

test_script:
  - pipenv run py.test

