build: "off"

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  #- "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip --version"
  - "pip install pipenv"
  - "pipenv install --dev --skip-lock"

test_script:
  - "pipenv run py.test"

